#!/usr/bin/env bun
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { basename, dirname, join } from 'node:path'

type OfficialBridge = { typeName: string; names: string[] }

const repo = process.argv[2] ?? process.env.BRIDGE_MANAGER_REPO ?? join(homedir(), 'projects', 'bridge-manager')
const root = join(import.meta.dir, '..')
const outputPath = join(root, 'src', 'lib', 'bridges', 'generated.ts')

const bridgeutil = await readFile(join(repo, 'cmd', 'bbctl', 'bridgeutil.go'), 'utf8')
const config = await readFile(join(repo, 'cmd', 'bbctl', 'config.go'), 'utf8')
const templateDir = join(repo, 'bridgeconfig')
const templateFiles = (await readdir(templateDir)).filter(file => file.endsWith('.tpl.yaml')).sort()
const templates: Record<string, string> = {}
for (const file of templateFiles) templates[file] = await readFile(join(templateDir, file), 'utf8')

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, `${renderGenerated({
  bridgeIPSuffix: parseStringMap(config, 'bridgeIPSuffix'),
  officialBridges: parseOfficialBridges(bridgeutil),
  templates,
  websocketBridges: parseBoolMap(bridgeutil, 'websocketBridges'),
})}\n`)

process.stderr.write(`Synced ${templateFiles.length} bridge templates from ${repo} to ${outputPath}\n`)

function renderGenerated(data: {
  bridgeIPSuffix: Record<string, string>
  officialBridges: OfficialBridge[]
  templates: Record<string, string>
  websocketBridges: Record<string, boolean>
}): string {
  const supportedBridges = Object.keys(data.templates).map(file => basename(file, '.tpl.yaml')).sort()
  return `// Generated by scripts/sync-bridge-manager-config.ts from bridge-manager. Do not edit by hand.

export type GeneratedOfficialBridge = { typeName: string; names: string[] }

export const generatedTemplates: Record<string, string> = ${JSON.stringify(data.templates, null, 2)} as const

export const generatedSupportedBridges = ${JSON.stringify(supportedBridges, null, 2)} as const

export const generatedOfficialBridges: GeneratedOfficialBridge[] = ${JSON.stringify(data.officialBridges, null, 2)}

export const generatedWebsocketBridges: Record<string, boolean> = ${JSON.stringify(data.websocketBridges, null, 2)}

export const generatedBridgeIPSuffix: Record<string, string> = ${JSON.stringify(data.bridgeIPSuffix, null, 2)}
`
}

function parseOfficialBridges(source: string): OfficialBridge[] {
  const body = mustMatch(source, /var officialBridges = \[\]bridgeTypeToNames\{([\s\S]*?)\n\}/, 'officialBridges')
  return [...body.matchAll(/\{"([^"]+)",\s*\[\]string\{([^}]*)\}\}/g)].map(match => ({
    typeName: match[1]!,
    names: [...match[2]!.matchAll(/"([^"]+)"/g)].map(name => name[1]!),
  }))
}

function parseBoolMap(source: string, name: string): Record<string, boolean> {
  const body = mustMatch(source, new RegExp(`var ${name} = map\\[string\\]bool\\{([\\s\\S]*?)\\n\\}`), name)
  const out: Record<string, boolean> = {}
  for (const match of body.matchAll(/"([^"]+)"\s*:\s*(true|false)/g)) out[match[1]!] = match[2] === 'true'
  return out
}

function parseStringMap(source: string, name: string): Record<string, string> {
  const body = mustMatch(source, new RegExp(`var ${name} = map\\[string\\]string\\{([\\s\\S]*?)\\n\\}`), name)
  const out: Record<string, string> = {}
  for (const match of body.matchAll(/"([^"]+)"\s*:\s*"([^"]*)"/g)) out[match[1]!] = match[2]!
  return out
}

function mustMatch(source: string, pattern: RegExp, name: string): string {
  const match = source.match(pattern)
  if (!match) throw new Error(`Failed to parse ${name} from bridge-manager Go source`)
  return match[1]!
}
